// defaultContent.js
// Server-side seed copy of content.js (as plain data, matching the shape
// expected there). Used to populate the database the first time the app
// runs, and as a fallback if any field is ever missing after an edit.
// Keep this in sync with public/content.js's default values.

module.exports = {
  pageTitle: 'CYOA ClipCatch',
  login: {
    heading: 'CYOA ClipCatch',
    usernamePlaceholder: 'Username',
    passwordPlaceholder: 'Password',
    loginButton: 'Log In',
    errorIncorrect: 'Incorrect username or password.',
  },
  topbar: {
    deletedButton: 'Deleted Files',
    newAlbumButton: 'New Capture',
  },
  footer: {
    settingsLink: 'Settings',
    logoutLink: 'Log out',
  },
  albumList: {
    statusCapturing: 'Capturing',
    statusScheduled: 'Scheduled',
    statusDone: 'Done',
  },
  albumForm: {
    titleNew: 'New Capture',
    titleEdit: 'Capture Settings',
    nameLabel: 'Name',
    namePlaceholder: 'eg. Reading Festival 2026',
    startLabel: 'Start',
    startPlaceholder: 'Select Start Date',
    startLockedNote: 'Already Started (locked).',
    endLabel: 'End',
    endPlaceholder: 'Select End Date',
    endLockedNote: 'Already Ended (locked).',
    saveButtonNew: 'Schedule',
    saveButtonStartNow: 'Start Capture',
    saveButtonEdit: 'Save Changes',
    startCapturingNowLink: 'Start Capturing Now',
    longCaptureWarning: 'Your capture is scheduled to last over {days} days. Are you sure?',
    missingDatesWarning: 'Please select both a start and end time before saving.',
    missingNameWarning: 'Please enter a name for this capture before saving.',
    endBeforeStartWarning: 'The end date/time must be after the start date/time.',
    savedToast: 'Capture saved.',
  },
  clients: {
    addFirstClientHeading: 'Add your first client',
    nameLabel: 'Client name',
    namePlaceholder: 'e.g. Olivia Dean',
    igIdLabel: 'Instagram Business account ID',
    igIdPlaceholder: 'From Meta\u2019s dashboard',
    tokenLabel: 'Access token',
    tokenPlaceholder: 'Generated in Meta\u2019s developer dashboard',
    addButton: 'Add client',
    editHeading: 'Edit client',
    saveButton: 'Save changes',
    deleteButton: 'Delete client',
    deleteConfirm: 'Delete this client and all of its captures? This cannot be undone.',
    missingNameWarning: 'Please enter a client name.',
    saveFailedWarning: 'Something went wrong saving these changes. Please try again.',
    addFailedWarning: 'Something went wrong adding this client. Please try again.',
    savedToast: 'Client saved.',
  },
  picker: { timeLabel: 'Time', cancelButton: 'Cancel', doneButton: 'Done' },
  videos: {
    sortNewest: 'Newest First',
    sortOldest: 'Oldest First',
    sortAlphabetical: 'Alphabetical',
    downloadStarredConfirm: 'You\u2019re about to download {count} files as a .zip. Are you sure?',
    deleteMarkedConfirm: 'You\u2019re about to delete {count} files. Are you sure?',
    deleteSingleToast: '1 file deleted.',
    deleteMultipleToast: '{count} files deleted.',
    albumDeletedToast: 'Capture deleted.',
    undoLink: 'Undo',
  },
  deletedFiles: {
    titleSuffix: '\u2014 deleted files',
    retentionNote: 'Kept for 30 days, then permanently removed.',
    restoreButton: 'Restore',
    notBuiltYetNote: 'Deleted files listing endpoint not yet built server-side.',
  },
  preview: {
    hintRow: 'Space: Play/Pause \u00b7 \u2190\u2192: Scrub 5s \u00b7 \u2191\u2193: Prev/Next \u00b7 S: Save \u00b7 D: Delete',
  },
  settings: {
    heading: 'General Settings',
    logoLabel: 'Logo (PNG)',
    logoUploadButton: 'Upload logo',
    customCssLabel: 'Custom CSS',
    customCssPlaceholder: '/* CSS entered here overrides the site\u2019s base styles */',
    textLabel: 'Site wording',
    saveButton: 'Save settings',
    savedToast: 'Settings saved.',
  },
};
